services:
  postgres:
    build:
      context: ./.dev/postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=default
      - POSTGRES_USER=default
      - POSTGRES_PASSWORD=secret
    networks:
      - app
networks:
  app:
    driver: bridge

volumes:
  postgres:
    driver: local
